type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = "COMP3511: Legal Aspects and Ethics of Computing"
subtitle = "Teaching Assistant"
date = "Spring 2024"
content = "The Hong Kong Polytechnic University"
tags = ["PolyU", "Ethics"]

[[items]]
title = "COMP1012: Programming Fundamentals and Applications (Python)"
subtitle = "Teaching Assistant"
date = "Fall 2023"
content = "The Hong Kong Polytechnic University"
tags = ["PolyU", "Python", "Programming"]

[[items]]
title = "COMP1011: Programming Fundamentals (C++)"
subtitle = "Teaching Assistant"
date = "Spring 2023"
content = "The Hong Kong Polytechnic University"
tags = ["PolyU", "C++", "Programming"]

[[items]]
title = "COMP1011: Programming Fundamentals (Java)"
subtitle = "Teaching Assistant"
date = "Fall 2022"
content = "The Hong Kong Polytechnic University"
tags = ["PolyU", "Java", "Programming"]
